"""add order-user and cart-user relationships

Revision ID: f395c33502d4
Revises: 3e40b5325dc8
Create Date: 2026-08-30 18:22:14.409848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f395c33502d4'
down_revision: Union[str, Sequence[str], None] = '3e40b5325dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('commentary', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=False))
    op.drop_column('orders', 'delivery_adress')
    op.drop_column('orders', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_adress', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'commentary')
    # ### end Alembic commands ###
